bootcamp_jobeet_homepage:
    path:     /
    defaults: { _controller: BootcampJobeetBundle:Default:index }

BootcampJobeetBundle_job:
    resource: "@BootcampJobeetBundle/Resources/config/routing/job.yml"
    prefix:   /admin/job
    
BootcampJobeetBundle_admin_category:
    resource: "@BootcampJobeetBundle/Resources/config/routing/category.yml"
    prefix:   /admin/category